name: "vmwiz-prod"

networks:
  vmwiz-internal:
    external: false

services:
  vmwiz-caddy:
    container_name: vmwiz-caddy
    image: caddy:2.8.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - vmwiz-internal
    cap_add:
      - NET_ADMIN
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/Caddy/caddy_data:/data
      - ./data/Caddy/caddy_config:/config
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    env_file:
      - ../.prod.env

  vmwiz-backend:
    container_name: vmwiz-backend
    image: docker.git.sos.ethz.ch/vsos/vmwiz.vsos.ethz.ch/backend:latest
    restart: unless-stopped
    expose:
      - 8081
    networks:
      - vmwiz-internal
    volumes:
      - ./ssh:/root/.ssh
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    env_file:
      - ../.prod.env
      - ../.db.prod.env
      - ../.backend.prod.env
    depends_on:
      vmwiz-db:
        condition: service_healthy

  vmwiz-cli:
    container_name: vmwiz-cli
    build:
      context: ../vmwiz-backend
      dockerfile: Dockerfile.cli
    restart: no
    networks:
      - vmwiz-internal
    command: ["/app/vwcli"]
    volumes:
      - ./ssh:/root/.ssh
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    env_file:
      - ../.prod.env
      - ../.db.prod.env
      - ../.backend.prod.env
  
  vmwiz-notifier:
    container_name: vmwiz-notifier
    image: caronc/apprise:1.1.5
    restart: unless-stopped
    networks:
      - vmwiz-internal
    volumes:
      - ${PWD}/notifier_config.yml:/config/default.yml
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - "8000:8000" 
    environment:
      - APPRISE_STATEFUL_MODE=simple
      - APPRISE_DEFAULT_CONFIG_ID=default	
      - APPRISE_WORKER_COUNT=1
  
  vmwiz-db:
    container_name: vmwiz-db
    image: postgres:latest
    restart: unless-stopped
    networks:
      - vmwiz-internal
    expose:
      - "5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    env_file:
      - ../.db.prod.env
    healthcheck:
      test: [
        "CMD-SHELL", 
        "psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1' || exit 1"
      ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s



  vmwiz-frontend:
    container_name: vmwiz-frontend
    image: docker.git.sos.ethz.ch/vsos/vmwiz.vsos.ethz.ch/frontend:latest
    restart: unless-stopped
    expose:
      - 8080
      - 443
    networks:
      - vmwiz-internal
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    working_dir: /app
